//! AGF Compliance Rule Evaluator — SP1 Guest Program
//!
//! This program runs INSIDE the SP1 zkVM. It reads compliance rule inputs from the host,
//! evaluates them deterministically, and commits the results as public values.
//!
//! The ZK proof generated by SP1 cryptographically attests that:
//! 1. These specific rules were evaluated
//! 2. Against these specific inputs
//! 3. Producing these specific PASS/BLOCK decisions
//! 4. Using EXACTLY this deterministic logic
//!
//! Reference: AGF OpenSpec v1.0, Section 8.2 — Test A: SP1 Feasibility Benchmark

#![no_main]
sp1_zkvm::entrypoint!(main);

use agf_lib::{evaluate_batch, ComplianceBatch, ComplianceBatchResult};

pub fn main() {
    // -----------------------------------------------------------------------
    // Step 1: Read compliance rule inputs from the host
    // -----------------------------------------------------------------------
    // These inputs are provided by the host script via SP1Stdin.
    // Inside the zkVM, they become part of the proven computation.
    let batch: ComplianceBatch = sp1_zkvm::io::read();

    // -----------------------------------------------------------------------
    // Step 2: Evaluate all compliance rules deterministically
    // -----------------------------------------------------------------------
    // This is the core AGF logic — every rule is checked against its threshold.
    // The evaluation is 100% deterministic: same input → same output, always.
    let result: ComplianceBatchResult = evaluate_batch(&batch);

    // -----------------------------------------------------------------------
    // Step 3: Commit results as public values
    // -----------------------------------------------------------------------
    // Public values are visible to anyone who verifies the proof.
    // They prove WHAT was decided without revealing HOW (the internal state).
    //
    // We commit:
    // - Total rules evaluated
    // - Pass/Block counts
    // - Whether all rules passed (the critical PASS/BLOCK decision)
    // - Each individual rule result
    sp1_zkvm::io::commit(&result.total_rules);
    sp1_zkvm::io::commit(&result.pass_count);
    sp1_zkvm::io::commit(&result.block_count);
    sp1_zkvm::io::commit(&result.all_compliant);

    // Commit each individual result for full transparency
    for r in &result.results {
        sp1_zkvm::io::commit(&r.rule_id);
        sp1_zkvm::io::commit(&r.compliant);
        sp1_zkvm::io::commit(&r.actual_value);
        sp1_zkvm::io::commit(&r.threshold_used);
        sp1_zkvm::io::commit(&r.margin_bps);
    }
}
